// Structured curricula — pre-authored syllabi for a SINGLE technology.
//
// The third way to start a course, sitting between the two that already exist:
//
//   generated course : the learner picks a technology, answers two questions, and a
//                      grounded model invents the topic list (agents/snowflake.ts).
//   career path      : a fixed, multi-technology curriculum written in paths.ts.
//   curriculum       : THIS — a fixed, single-technology syllabus, deep enough to be
//                      the whole subject rather than one course's worth of it.
//
// WHY a third: a generated roadmap is a dozen topics expanded on demand, which is the
// right shape for "teach me some Rust" and the wrong one for "teach me C++". A language
// has a canonical order — you cannot teach references before objects, or virtual
// dispatch before inheritance — and asking a model to rediscover that order per learner
// produces a different, shallower course every time. So the ORDER is authored here and
// the TEACHING is still generated: every lesson's text, exercise and objectives come
// from the lesson agent, per learner, at their level.
//
// Shape maps onto the roadmap tree the rest of the app already renders:
//
//     curriculum -> Roadmap
//     chapter    -> topic  (t0, t1, …)
//     lesson     -> point  (t0-p0, t0-p1, …)   <- a LEAF: "Start lesson", no expansion
//
// Note the missing level. A generated course and a path both put subtopics between the
// topic and the lesson, because their leaves are invented and something has to hold the
// invention. Here the leaves ARE the syllabus, so a subtopic layer would be a fabricated
// grouping sitting between two authored ones. Chapters carry their lessons directly, and
// `children` is a real array rather than null — which is what stops the expander from
// generating anything, and what makes opening one of these courses cost zero LLM calls
// until the learner actually starts a lesson.

import type { Roadmap, RoadmapNode } from "@/lib/agents/snowflake";

/**
 * One lesson. A bare string is title-only; the object form adds a SCOPE LINE.
 *
 * The scope line is the difference between a syllabus and a list of nouns. "Struct
 * miscellany" tells the lesson agent nothing — it will invent a scope, and two learners
 * asking for the same slot get materially different lessons. Worse, neighbouring
 * lessons ("part 2", "part 3") overlap, because nothing tells either one where its
 * boundary is. So the summary says what this lesson covers AND what it must leave
 * alone because a later lesson owns it.
 *
 * Same idea as PathChapter's optional summary in paths.ts, for the same reason.
 */
export type CurriculumLesson = string | { title: string; summary: string };

export type CurriculumChapter = {
  title: string;
  /** Shown under the chapter in the roadmap, and given to the lesson agent as context. */
  summary: string;
  /** Each becomes one lesson. Ordered; the order is the pedagogy. */
  lessons: CurriculumLesson[];
};

export function lessonTitle(l: CurriculumLesson): string {
  return typeof l === "string" ? l : l.title;
}
export function lessonSummary(l: CurriculumLesson): string {
  return typeof l === "string" ? "" : l.summary;
}

export type Curriculum = {
  /** RUNTIMES id — the module this replaces generation for. */
  module: string;
  title: string;
  summary: string;
  goal: string;
  chapters: CurriculumChapter[];
};

// ---------------------------------------------------------------------------
// C++
// ---------------------------------------------------------------------------
//
// Sequence adapted from the chapter order LearnCpp.com established — the ordering is
// the part worth borrowing, and a topic order is not what copyright protects. NONE of
// its prose is used, reproduced or paraphrased: every lesson's teaching text, exercise,
// starter code and objectives are generated by our own lesson agent against real
// current documentation (DevDocs' cppreference mirror, see lib/docs.ts).
//
// CURATED FOR THIS RUNTIME, which is the reason this is not a transcription. The C++
// module is real clang++ compiled to WebAssembly (runtimes/engineC.ts), and its limits
// are hard. Lessons that cannot be written, run and graded here are NOT in the list:
//
//   • EXCEPTIONS ARE ABSENT ENTIRELY. The wasip1 sysroot's libc++ ships without an
//     unwinder, so the module is compiled -fno-exceptions and `try`/`throw`/`catch` are
//     COMPILE ERRORS. An entire upstream chapter (the need for exceptions, stack
//     unwinding, catch-all handlers, rethrowing, function try blocks, noexcept,
//     std::move_if_noexcept) is therefore unteachable here — not omitted for being
//     unimportant. Error handling is taught the way the runtime allows instead, in
//     "Error Detection and Handling": return codes, std::optional, validity flags and
//     checking before acting. THIS IS A REAL GAP IN THE COURSE and the summary says so.
//   • ONE TRANSLATION UNIT. main.cc is the only file, so multiple code files, header
//     files, header guards, sharing constants across files and templates across files
//     are all gone. Internal/external linkage survives — it still compiles and still
//     explains `static` and `extern` — but there is no second file to link against.
//   • NO STDIN. std::cin hits end-of-file immediately, so input parsing and stream
//     validation are taught through std::istringstream, which reads a string and
//     behaves identically for everything the lessons are about.
//   • NO FILES, and no debugger. File I/O is gone; the debugging chapter keeps the
//     reasoning (how to isolate a fault, how to read a diagnostic) and drops the four
//     lessons that drive an IDE's stepper, breakpoints, watch window and call stack.
//   • NO TOOLCHAIN SETUP. Installing an IDE, choosing a language standard and
//     configuring warning levels are answered by the app itself — the compiler is
//     already here, already -std=c++20 -Wall. The conceptual half of that chapter
//     (what a compiler and linker actually do) is kept because it is worth knowing.
const CPP: Curriculum = {
  module: "cpp",
  title: "C++",
  summary:
    "Modern C++ from zero to virtual dispatch and templates, in the order the language " +
    "has to be learned: objects and types, functions and scope, control flow, references " +
    "and pointers, structs and classes, the containers, inheritance and polymorphism, " +
    "operator overloading, move semantics and smart pointers. Every lesson is compiled " +
    "and run for real by clang++ in your browser. Exceptions are not covered — this " +
    "compiler has no unwinder, so try/throw/catch cannot run here.",
  goal: "Write correct, modern C++ with confidence",
  chapters: [
    {
      title: "Getting Started",
      summary: "What a C++ program is, and what turns your text into something that runs.",
      lessons: [
        "Introduction to programs and programming languages",
        "Introduction to C and C++",
        "The compiler, the linker, and libraries",
        "Compiling your first program",
      ],
    },
    {
      title: "C++ Basics",
      summary: "Statements, objects, variables and output — the smallest complete program.",
      lessons: [
        "Statements and the structure of a program",
        "Comments",
        "Introduction to objects and variables",
        "Variable assignment and initialization",
        "Introduction to iostream and std::cout",
        "Uninitialized variables and undefined behavior",
        "Keywords and naming identifiers",
        "Whitespace and basic formatting",
        "Introduction to literals and operators",
        "Introduction to expressions",
        "Developing your first program",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Functions",
      summary: "Naming a piece of work: returns, parameters, scope, and why functions pay off.",
      lessons: [
        "Introduction to functions",
        "Function return values",
        "Void functions",
        "Function parameters and arguments",
        "Introduction to local scope",
        "Why functions are useful, and how to use them effectively",
        "Forward declarations and definitions",
        "Naming collisions and an introduction to namespaces",
        "Introduction to the preprocessor",
        "How to design your first programs",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Debugging C++ Programs",
      summary: "Finding the fault yourself — reading diagnostics, isolating, and printing.",
      lessons: [
        "Syntax and semantic errors",
        "The debugging process",
        "A strategy for debugging",
        "Basic debugging tactics",
        "More debugging tactics: instrumenting your code",
        "Finding issues before they become problems",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Fundamental Data Types",
      summary: "The built-in types, their sizes, and the first conversions between them.",
      lessons: [
        "Introduction to fundamental data types",
        "Void",
        "Object sizes and the sizeof operator",
        "Signed integers",
        "Unsigned integers, and why to avoid them",
        "Fixed-width integers and size_t",
        "Introduction to scientific notation",
        "Floating point numbers",
        "Boolean values",
        "Introduction to if statements",
        "Chars",
        "Introduction to type conversion and static_cast",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Constants and Strings",
      summary: "Values that must not change, compile-time evaluation, and text.",
      lessons: [
        "Constant variables (named constants)",
        "Literals",
        "Numeral systems: decimal, binary, hexadecimal and octal",
        "The as-if rule and compile-time optimization",
        "Constant expressions",
        "Constexpr variables",
        "Introduction to std::string",
        "Introduction to std::string_view",
        "std::string_view part 2: ownership and dangling",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Operators",
      summary: "Precedence, arithmetic, side effects, and the comparisons that surprise people.",
      lessons: [
        "Operator precedence and associativity",
        "Arithmetic operators",
        "Remainder and exponentiation",
        "Increment/decrement operators, and side effects",
        "The comma operator",
        "The conditional operator",
        "Relational operators and floating point comparisons",
        "Logical operators",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Bit Manipulation",
      summary: "Working a value one bit at a time — flags, masks and the bitwise operators.",
      lessons: [
        "Bit flags and bit manipulation via std::bitset",
        "Bitwise operators",
        "Bit manipulation with bitwise operators and bit masks",
        "Converting integers between binary and decimal representation",
      ],
    },
    {
      title: "Scope, Duration, and Linkage",
      summary: "Where a name is visible, how long its object lives, and what links to what.",
      lessons: [
        "Compound statements (blocks)",
        "User-defined namespaces and the scope resolution operator",
        "Local variables",
        "Introduction to global variables",
        "Variable shadowing (name hiding)",
        "Internal linkage",
        "External linkage and variable forward declarations",
        "Why non-const global variables are evil",
        "Inline functions and variables",
        "Static local variables",
        "Scope, duration, and linkage summary",
        "Using declarations and using directives",
        "Unnamed and inline namespaces",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Control Flow",
      summary: "Choosing and repeating: if, switch, the loops, and getting out early.",
      lessons: [
        "Control flow introduction",
        "If statements and blocks",
        "Common if statement problems",
        "Constexpr if statements",
        "Switch statement basics",
        "Switch fallthrough and scoping",
        "Goto statements",
        "Introduction to loops and while statements",
        "Do while statements",
        "For statements",
        "Break and continue",
        "Halts: exiting your program early",
        "Introduction to random number generation",
        "Generating random numbers using Mersenne Twister",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Error Detection and Handling",
      summary:
        "Being wrong safely WITHOUT exceptions — this compiler has no unwinder, so error " +
        "handling is return codes, std::optional, validity flags and asserts.",
      lessons: [
        "Introduction to testing your code",
        "Code coverage",
        "Common semantic errors in C++",
        "Detecting and handling errors without exceptions",
        "Returning failure: error codes and std::optional",
        "Assert and static_assert",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Type Conversion, Type Aliases, and Type Deduction",
      summary: "What converts to what, when it is safe, and letting the compiler name types.",
      lessons: [
        "Implicit type conversion",
        "Floating-point and integral promotion",
        "Numeric conversions",
        "Narrowing conversions, list initialization, and constexpr initializers",
        "Arithmetic conversions",
        "Explicit type conversion (casting) and static_cast",
        "Typedefs and type aliases",
        "Type deduction for objects using the auto keyword",
        "Type deduction for functions",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Function Overloading and Function Templates",
      summary: "One name, several functions — and one function, several types.",
      lessons: [
        "Introduction to function overloading",
        "Function overload differentiation",
        "Function overload resolution and ambiguous matches",
        "Deleting functions",
        "Default arguments",
        "Function templates",
        "Function template instantiation",
        "Function templates with multiple template types",
        "Non-type template parameters",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Constexpr Functions",
      summary: "Work the compiler does before the program ever runs.",
      lessons: [
        "Constexpr functions",
        "Constexpr functions part 2: when they run at compile time",
        "Constexpr functions part 3 and consteval",
        "Constexpr functions part 4: constexpr in practice",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Compound Types: References and Pointers",
      summary: "Referring to an object instead of copying it — the chapter C++ turns on.",
      lessons: [
        "Introduction to compound data types",
        "Value categories (lvalues and rvalues)",
        "Lvalue references",
        "Lvalue references to const",
        "Pass by lvalue reference",
        "Pass by const lvalue reference",
        "Introduction to pointers",
        "Null pointers",
        "Pointers and const",
        "Pass by address",
        "Pass by address part 2",
        "Return by reference and return by address",
        "In and out parameters",
        "Type deduction with pointers, references, and const",
        "std::optional",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Compound Types: Enums and Structs",
      summary: "Your own types at last — named alternatives, and grouped data.",
      lessons: [
        "Introduction to program-defined (user-defined) types",
        "Unscoped enumerations",
        "Unscoped enumerator integral conversions",
        "Converting an enumeration to and from a string",
        "Introduction to overloading the I/O operators",
        "Scoped enumerations (enum classes)",
        "Introduction to structs, members, and member selection",
        "Struct aggregate initialization",
        "Default member initialization",
        "Passing and returning structs",
        "Struct miscellany",
        "Member selection with pointers and references",
        "Class templates",
        "Class template argument deduction (CTAD) and deduction guides",
        "Alias templates",
        "Using a language reference",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Introduction to Classes",
      summary: "Data and the code that maintains it, together — construction and invariants.",
      lessons: [
        "Introduction to object-oriented programming",
        "Introduction to classes",
        "Member functions",
        "Const class objects and const member functions",
        "Public and private members and access specifiers",
        "Access functions",
        "Member functions returning references to data members",
        "The benefits of data hiding (encapsulation)",
        "Introduction to constructors",
        "Constructor member initializer lists",
        "Default constructors and default arguments",
        "Delegating constructors",
        "Temporary class objects",
        "Introduction to the copy constructor",
        "Class initialization and copy elision",
        "Converting constructors and the explicit keyword",
        "Constexpr aggregates and classes",
        "Chapter review and quiz",
      ],
    },
    {
      title: "More on Classes",
      summary: "this, destructors, statics, friends — the rest of what a class can do.",
      lessons: [
        "The hidden this pointer and member function chaining",
        "Nested types (member types)",
        "Introduction to destructors",
        "Class templates with member functions",
        "Static member variables",
        "Static member functions",
        "Friend non-member functions",
        "Friend classes and friend member functions",
        "Ref qualifiers",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Dynamic Arrays: std::vector",
      summary: "The container you should reach for first, and the loops that walk it.",
      lessons: [
        "Introduction to containers and arrays",
        "Introduction to std::vector and list constructors",
        "std::vector and the unsigned length and subscript problem",
        "Passing std::vector",
        "Returning std::vector, and an introduction to move semantics",
        "Arrays and loops",
        "Arrays, loops, and sign challenge solutions",
        "Range-based for loops (for-each)",
        "Array indexing and length using enumerators",
        "std::vector resizing and capacity",
        "std::vector and stack behavior",
        "std::vector<bool> and why it is not a vector",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Fixed-size Arrays: std::array and C-style Arrays",
      summary: "Fixed-length storage, and the raw arrays underneath everything.",
      lessons: [
        "Introduction to std::array",
        "std::array length and indexing",
        "Passing and returning std::array",
        "std::array of class types, and brace elision",
        "Arrays of references via std::reference_wrapper",
        "std::array and enumerations",
        "Introduction to C-style arrays",
        "C-style array decay",
        "Pointer arithmetic and subscripting",
        "C-style strings",
        "C-style string symbolic constants",
        "Multidimensional C-style arrays",
        "Multidimensional std::array",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Iterators and Algorithms",
      summary: "The standard library's own loop — and why you should stop writing yours.",
      lessons: [
        "Sorting an array using selection sort",
        "Introduction to iterators",
        "Introduction to standard library algorithms",
        "Timing your code",
      ],
    },
    {
      title: "Dynamic Allocation",
      summary: "Memory you ask for and must give back — new, delete, and what leaks.",
      lessons: [
        "Dynamic memory allocation with new and delete",
        "Dynamically allocating arrays",
        "Destructors and cleaning up",
        "Pointers to pointers and dynamic multidimensional arrays",
        "Void pointers",
      ],
    },
    {
      title: "Functions, Lambdas, and the Call Stack",
      summary: "Functions as values, where locals actually live, and recursion.",
      lessons: [
        "Function pointers",
        "The stack and the heap",
        "Recursion",
        "Ellipsis, and why to avoid them",
        "Introduction to lambdas (anonymous functions)",
        "Lambda captures",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Operator Overloading",
      summary: "Making your type behave like a built-in — carefully.",
      lessons: [
        "Introduction to operator overloading",
        "Overloading the arithmetic operators using friend functions",
        "Overloading operators using normal functions",
        "Overloading the I/O operators",
        "Overloading operators using member functions",
        "Overloading unary operators +, -, and !",
        "Overloading the comparison operators",
        "Overloading the increment and decrement operators",
        "Overloading the subscript operator",
        "Overloading the parenthesis operator",
        "Overloading typecasts",
        "Overloading the assignment operator",
        "Shallow vs. deep copying",
        "Overloading operators and function templates",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Move Semantics and Smart Pointers",
      summary: "Transferring ownership instead of copying it, and never calling delete again.",
      lessons: [
        "Introduction to smart pointers and move semantics",
        "R-value references",
        "Move constructors and move assignment",
        "std::move",
        "std::unique_ptr",
        "std::shared_ptr",
        "Circular dependencies with std::shared_ptr, and std::weak_ptr",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Object Relationships",
      summary: "How one type can be built from, hold, or merely know about another.",
      lessons: [
        "Object relationships",
        "Composition",
        "Aggregation",
        "Association",
        "Dependencies",
        "Container classes",
        "std::initializer_list",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Inheritance",
      summary: "Building a type on top of another — and how construction really orders.",
      lessons: [
        "Introduction to inheritance",
        "Basic inheritance in C++",
        "Order of construction of derived classes",
        "Constructors and initialization of derived classes",
        "Inheritance and access specifiers",
        "Adding new functionality to a derived class",
        "Calling inherited functions and overriding behavior",
        "Hiding inherited functionality",
        "Multiple inheritance",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Virtual Functions",
      summary: "Polymorphism: one call, the right implementation, decided at run time.",
      lessons: [
        "Pointers and references to the base class of derived objects",
        "Virtual functions and polymorphism",
        "The override and final specifiers, and covariant return types",
        "Virtual destructors, virtual assignment, and overriding virtualization",
        "Early binding and late binding",
        "The virtual table",
        "Pure virtual functions, abstract base classes, and interface classes",
        "Virtual base classes",
        "Object slicing",
        "Dynamic casting",
        "Printing inherited classes using operator<<",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Templates and Classes",
      summary: "Generic types, and the escape hatches when generic is not quite right.",
      lessons: [
        "Template classes",
        "Template non-type parameters",
        "Function template specialization",
        "Class template specialization",
        "Partial template specialization",
        "Partial template specialization for pointers",
        "Chapter review and quiz",
      ],
    },
    {
      title: "Input and Output",
      summary:
        "The stream library. Input is taught with std::istringstream — this runtime has " +
        "no stdin, so std::cin sees end-of-file immediately.",
      lessons: [
        "Input and output (I/O) streams",
        "Output with ostream and ios",
        "Stream classes for strings",
        "Parsing input with std::istringstream",
        "Stream states and input validation",
      ],
    },
    {
      title: "Modern C++ in Practice",
      summary: "What each standard added, and the habits worth keeping from them.",
      lessons: [
        "What C++11 introduced",
        "What C++14 introduced",
        "What C++17 introduced",
        "What C++20 introduced: concepts, ranges and std::format",
        "Putting it together: writing modern, idiomatic C++",
      ],
    },
  ],
};

// ---------------------------------------------------------------------------

const CURRICULA: Curriculum[] = [CPP];

/** The structured curriculum for a module, if one is authored. */
export function getCurriculum(moduleId?: string | null): Curriculum | null {
  return moduleId ? CURRICULA.find((c) => c.module === moduleId) ?? null : null;
}

/** How many lessons a curriculum holds — for the "N lessons" line on a card. */
export function curriculumLessonCount(c: Curriculum): number {
  return c.chapters.reduce((n, ch) => n + ch.lessons.length, 0);
}

/**
 * The whole curriculum as a roadmap tree, built locally — no generation call.
 *
 * Every lesson is emitted as a `point` with `children: []`. Both parts matter:
 * "point" is what renders a "Start lesson" button, and a non-null `children` is what
 * tells the expander there is nothing here to generate. A generated course fills its
 * leaves in on demand; this one already has them.
 *
 * The tree is identical at every level — a language's order does not change because
 * the learner is experienced. Level still reaches the lessons themselves, through
 * difficultyGuidance() in the lesson agent, which is where "experienced" should show
 * up: denser lessons on the same syllabus, not a different syllabus.
 */
export function curriculumRoadmap(c: Curriculum, level?: string, goal?: string): Roadmap {
  const topics: RoadmapNode[] = c.chapters.map((chapter, i) => ({
    id: `t${i}`,
    kind: "topic",
    title: chapter.title,
    summary: chapter.summary,
    module: c.module,
    children: chapter.lessons.map((lesson, j) => ({
      id: `t${i}-p${j}`,
      kind: "point" as const,
      title: lessonTitle(lesson),
      // Empty for a title-only lesson, which is what every entry still is until its
      // scope line is written. The lesson agent already handles an absent summary —
      // it just generates against the title alone, exactly as before.
      summary: lessonSummary(lesson),
      module: c.module,
      children: [],
    })),
  }));

  return {
    skill: c.title,
    title: c.title,
    summary: c.summary,
    level,
    goal: goal || c.goal,
    topics,
  };
}
