import type { Metadata } from "next";
import LegalPage, { A, type Section } from "@/components/LegalPage";
import { CONTACT_EMAIL, SITE_HOST, SITE_NAME, SITE_URL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service — CodeChad",
  description:
    "The terms you agree to when you use CodeChad: what the service is, what is expected of you, and the limits of what it promises.",
  alternates: { canonical: "/terms" },
};

const UPDATED = "26 July 2026";
const CONTACT = CONTACT_EMAIL;

const sections: Section[] = [
  {
    heading: "Agreeing to these terms",
    blocks: [
      {
        p: (
          <>
            By using {SITE_NAME} at{" "}
            <A href={SITE_URL}>{SITE_HOST}</A> you agree to these
            terms. If you do not agree with them, please do not use the service. They are a contract
            between you and the operator of CodeChad, a solo developer based in Portugal, reachable
            at <A href={`mailto:${CONTACT}`}>{CONTACT}</A>.
          </>
        ),
      },
    ],
  },
  {
    heading: "What CodeChad is",
    blocks: [
      {
        p: "CodeChad generates a personalised learning roadmap for a programming language or database, then teaches it lesson by lesson with an AI tutor, in an editor that runs your code live in the browser.",
      },
      {
        p: "It is beta software and a personal project. Features change, break and disappear. It is offered free of charge, with no guarantee that it will keep working, keep your data, or continue to exist.",
      },
    ],
  },
  {
    heading: "Your account",
    blocks: [
      {
        p: "You sign in with a Google account, a GitHub account, or an email address and a password you choose. You are responsible for that account and for anything done through it on CodeChad. If you set a password here, choose one you do not use anywhere else, and keep it to yourself. Tell us promptly if you believe someone else has used your account.",
      },
      {
        p: "You must be at least 16 years old to use CodeChad.",
      },
    ],
  },
  {
    heading: "Acceptable use",
    blocks: [
      { p: "Use CodeChad to learn. Do not:" },
      {
        list: [
          "Attempt to break out of the code sandbox, attack the service or its providers, or interfere with anyone else's use of it.",
          "Use the AI tutor to generate malware, content that harms others, or anything unlawful.",
          "Automate or scrape the service, or resell access to it.",
          "Upload personal data about other people, credentials or confidential material into the editor or chat.",
        ],
      },
      {
        p: "We may suspend or remove access if the service is being used this way. Given it is a free personal project, that decision is ours and may be immediate.",
      },
    ],
  },
  {
    heading: "AI-generated content",
    blocks: [
      {
        p: "Roadmaps, lessons, explanations and tutor replies are generated by an AI model. They can be incomplete, out of date or simply wrong, including when they sound confident. Exercise grading is deterministic — it runs your code and checks the result — but the teaching around it is not.",
      },
      {
        p: "Check anything that matters against the official documentation for the technology you are learning. Do not rely on CodeChad for professional, security or legal decisions.",
      },
    ],
  },
  {
    heading: "Your content",
    blocks: [
      {
        p: "The code you write and the messages you send remain yours. You grant us only the permission needed to operate the service: to store that content, and to send it to the AI provider so it can respond to you. We do not use it to train AI models, and we do not publish it.",
      },
      {
        p: "The roadmaps and lessons the service generates for you are yours to use freely, for any purpose.",
      },
    ],
  },
  {
    heading: "Availability and changes",
    blocks: [
      {
        p: "There is no uptime commitment. The service may be unavailable, may lose data, and may be discontinued at any time without notice. Third-party pieces it depends on — Google's AI models, Supabase, the browser runtimes — may change or stop working, and some of them impose usage quotas that can make generation fail temporarily.",
      },
      {
        p: (
          <>
            Keep your own copy of anything you would be sorry to lose. See the{" "}
            <A href="/privacy">Privacy Policy</A> for what we store and how to get it deleted.
          </>
        ),
      },
    ],
  },
  {
    heading: "No warranty",
    blocks: [
      {
        p: "CodeChad is provided “as is” and “as available”, without warranties of any kind, express or implied, including fitness for a particular purpose, accuracy of content, or uninterrupted operation. Nothing here excludes rights you have as a consumer under mandatory law.",
      },
    ],
  },
  {
    heading: "Limitation of liability",
    blocks: [
      {
        p: "To the fullest extent the law allows, we are not liable for indirect or consequential loss, lost data, lost profits, or anything arising from your reliance on AI-generated content. Because the service is free, our total liability to you is limited to what you have paid for it, which is nothing. Liability for death, personal injury, fraud, or anything else that cannot be excluded by law is unaffected.",
      },
    ],
  },
  {
    heading: "Ending it",
    blocks: [
      {
        p: (
          <>
            You may stop using CodeChad at any time, delete your courses from within the app, and
            ask us to delete your account by writing to{" "}
            <A href={`mailto:${CONTACT}`}>{CONTACT}</A>. We may end your access if you breach these
            terms or if the service is discontinued.
          </>
        ),
      },
    ],
  },
  {
    heading: "Governing law",
    blocks: [
      {
        p: "These terms are governed by Portuguese law, and disputes fall to the courts of Portugal. If you are a consumer resident elsewhere in the EU, you keep the protection of the mandatory laws of your own country and may bring proceedings there.",
      },
    ],
  },
  {
    heading: "Changes to these terms",
    blocks: [
      {
        p: "We may update these terms. The date at the top of this page shows when they last changed, and continuing to use CodeChad after a change means you accept the new version.",
      },
    ],
  },
  {
    heading: "Contact",
    blocks: [
      {
        p: (
          <>
            Questions about these terms go to <A href={`mailto:${CONTACT}`}>{CONTACT}</A>.
          </>
        ),
      },
    ],
  },
];

export default function Terms() {
  return (
    <LegalPage
      title="Terms of Service"
      updated={UPDATED}
      intro={
        <>
          CodeChad is free, in beta, and run by one person. These terms say what you can expect from
          it, what it expects from you, and what it does not promise — in particular that its AI
          tutor can be wrong and that your data is not guaranteed to survive.
        </>
      }
      sections={sections}
    />
  );
}
